### ISSUE TITLE
Some "Featured" Puppets not showing up in App

### ISSUE THREAD

**Issue by xaudiblex** [gitsponge/puppets#1]
When I go to the "Install puppets" section in the app, PBS Kids & Popcornflix do not show up in the list as available to install (completely missing in the install interface).  Please advise.

**Comment by gitsponge** [comment]
These are not featured but can be installed via pastebin

**Comment by gitsponge** [comment]
These are not featured but can be installed via pastebin:

PBS Kids (broken on video format): vhmjxhan
popcornflix: ug33uugq

**Comment by xaudiblex** [comment]
That is good to know.  Thanks!

**Comment by xaudiblex** [comment]
By any chance, has the popcornflix app been updated?  I tried to reinstall using the pastebin and it says unable to install...
